version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_nest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_nest
    restart: always
    ports:
      - "8090:8080"

volumes:
  postgres_data:
